Fix Mobile Vikings MNC code was not correct so link fot more info on …
sailfishos/mobile-broadband-provider-info pull request #21
Opened 2024-02-12 19:15 UTC by ruditimmermans

…the Mobile Vikings website.

https://support.mobilevikings.be/hc/nl/articles/202836041-Ik-heb-geen-mobiel-internet-Wat-moet-ik-doen

2024-02-20 12:12 UTC, pvuorela approved these changes
Based on forum and the mobile vikings website there seems to be a bit conflicting information, but none having the current mnc 20. If this gets it working for you, I'm assumign it's for the better.

2024-02-20 12:16 UTC, pvuorela requested changes

2024-02-20 12:16 UTC, pvuorela commented on mobile-broadband-provider-info/serviceproviders.xml
> +				<name>Mobile Vikings Internet</name>
This needs to be below the <usage>. Otherwise the xml doesn't validate and build fails.

2024-02-20 12:19 UTC, mlehtima approved these changes

2024-02-20 12:53 UTC, pvuorela reviewed
Looks better now, but could you still rebase and squash the commits to avoid intermediate steps in the git history. I.e. git rebase -i origin/master and mark the latter commit with 's'.

2024-02-20 13:38 UTC, ruditimmermans commented
> Looks better now, but could you still rebase and squash the commits to avoid intermediate steps in the git history. I.e. git rebase -i origin/master and mark the latter commit with 's'.

I'm sorry i work directly online via the Github website and i never used Git itself on Windows so this is my first time i have dont something like this sorry....

2024-02-20 13:49 UTC, pvuorela commented
> I'm sorry i work directly online via the Github website and i never used Git itself on Windows so this is my first time i have dont something like this sorry....

Ah, interesting. But no worries, I can also do some squashing with the merging. Just commonly better if PR author handles that.

2024-02-20 13:49 UTC, pvuorela approved these changes

2024-02-20 13:51 UTC, merged

2024-02-20 13:52 UTC, ruditimmermans commented
> > I'm sorry i work directly online via the Github website and i never used Git itself on Windows so this is my first time i have dont something like this sorry....
> 
> Ah, interesting. But no worries, I can also do some squashing with the merging. Just commonly better if PR author handles that.

Ok i understand i will look on git how this works for into the future i do something myself, thanks for the helps!

2024-02-28 06:23 UTC, ruditimmermans commented
Hi Pekka,

I was into a talk with Jussi into a private message on the forum and we found out my mobile network would be crashing with Offono i send the offono logs back to Jussi but i dont hear anything more, would i need to send the logs to you also or someone elsse ?

Thanks!
Rudi